<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $restaurant->name }} - Menu</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; line-height: 1.6; }
        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
        .logo { font-size: 32px; font-weight: bold; color: #1a5f3d; }
        .cuisine { font-size: 14px; text-transform: uppercase; letter-spacing: 2px; color: #666; }
        .category { margin-top: 40px; page-break-inside: avoid; }
        .category-title { font-size: 24px; border-left: 5px solid #1a5f3d; padding-left: 10px; margin-bottom: 20px; background: #f9f9f9; }
        .item { margin-bottom: 15px; border-bottom: 1px dotted #ccc; padding-bottom: 5px; }
        .item-name { font-size: 18px; font-weight: bold; }
        .item-price { float: right; font-weight: bold; color: #1a5f3d; }
        .item-description { font-size: 12px; color: #777; margin-top: 2px; }
        .footer { text-align: center; margin-top: 50px; font-size: 10px; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">{{ $restaurant->name }}</div>
        <div class="cuisine">{{ $restaurant->cuisine_type }}</div>
        <div style="margin-top: 10px;">{{ $restaurant->address }} | {{ $restaurant->phone }}</div>
    </div>

    @foreach($categories as $category)
        <div class="category">
            <div class="category-title">{{ $category->name }}</div>
            @foreach($category->menuItems as $item)
                <div class="item">
                    <span class="item-price">Rs {{ number_format($item->price, 0) }}</span>
                    <div class="item-name">{{ $item->name }}</div>
                    @if($item->description)
                        <div class="item-description">{{ $item->description }}</div>
                    @endif
                </div>
            @endforeach
        </div>
    @endforeach

    <div class="footer">
        Generated by {{ config('app.name') }} | {{ now()->format('Y-m-d H:i') }}
    </div>
</body>
</html>
